name: "CI workflow"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "python:3.9-slim"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Lint with flake8"
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: "Run unit tests with nose"
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

      # New cleanup step
      - name: "Cleanup workspace"
        run: |
          echo "Removing all files from workspace..."
          WORKSPACE_SOURCE_PATH="${GITHUB_WORKSPACE}"  # GitHub workspace path
          if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
            # Delete non-hidden files and directories
            rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
            # Delete files and directories starting with . but excluding ..
            rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]* 
            # Delete files and directories starting with .. plus any other character
            rm -rf "${WORKSPACE_SOURCE_PATH}"/..?* 
          fi
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}  # This environment variable holds the GitHub workspace path
